from typing import List, Optional, Dict, Any
from pydantic import BaseModel
from datetime import datetime

class DashboardItemBase(BaseModel):
    id: str  # Frontend generates UUIDs for items usually, or we can let backend do it
    type: str
    title: Optional[str] = None
    config: Dict[str, Any]

class DashboardItemCreate(DashboardItemBase):
    pass

class DashboardItem(DashboardItemBase):
    dashboard_id: str
    created_at: datetime

class DashboardBase(BaseModel):
    name: str
    description: Optional[str] = None

class DashboardCreate(DashboardBase):
    id: Optional[str] = None # Allow setting ID if desired, otherwise backend/db could handle it if we used serial, but here we use VARCHAR ID so likely UUID from frontend or generated by backend

class DashboardUpdate(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None

class Dashboard(DashboardBase):
    id: str
    created_at: datetime
    updated_at: datetime
    items: List[DashboardItem] = []

class DashboardLayoutUpdate(BaseModel):
    items: List[DashboardItemCreate]
